// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assignment4;

namespace assignment4.Migrations
{
    [DbContext(typeof(ShoppingContext))]
    [Migration("20190921105036_assignment")]
    partial class assignment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("assignment4.book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("author");

                    b.Property<string>("barcode");

                    b.Property<int>("bookId");

                    b.Property<int>("copycount");

                    b.Property<string>("edition");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("assignment4.student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("fine");

                    b.Property<int>("studentId");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("assignment4.studentbook", b =>
                {
                    b.Property<int>("studentId");

                    b.Property<int>("bookId");

                    b.Property<DateTime>("issuedate");

                    b.Property<DateTime>("returneDate");

                    b.HasKey("studentId", "bookId");

                    b.HasIndex("bookId");

                    b.ToTable("Studentbooks");
                });

            modelBuilder.Entity("assignment4.studentbook", b =>
                {
                    b.HasOne("assignment4.book", "book")
                        .WithMany("books")
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("assignment4.student", "student")
                        .WithMany("books")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
